import Head from "next/head";
import React, {FC} from 'react';

type HeadProps = {
  title: string;
  description: string
};

const Header:FC<HeadProps> = ({title, description}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name={description} content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
